on:
  push:
    branches: 
      - deploy

name: Deploy to Amazon ECS

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Poetry
      run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    
    - name: Poetry export requirements
      run: ~/.poetry/bin/poetry export -f requirements.txt > requirements.txt
      
    - name: Docker Build and Push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: raccoonhj33/project-omok
        tags: latest

    - name: Login to EC2 and Server Init
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.OMOK_PEM }}
        script: |
          docker pull raccoonhj33/project-omok
          docker stop omok redis && docker system prune
          docker run -d --rm -p 6379:6379 --name redis redis:5
          docker run -d -it --rm -p 80:80 -p 443:443 --name omok -e DJANGO_SETTINGS_MODULE=config.settings.prod -v ~/.aws:/root/.aws -v /etc/letsencrypt:/etc/letsencrypt -v ~/secrets.json:/srv/project-omok/secrets.json raccoonhj33/project-omok bash
          docker exec omok supervisord -c /srv/project-omok/.config/supervisord.conf
